# Generated by Django 6.0 on 2025-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Testo della domanda')),
                ('question_type', models.CharField(choices=[('closed', 'Chiusa'), ('open', 'Aperta')], default='closed', max_length=10, verbose_name='Tipo di domanda')),
                ('options', models.JSONField(blank=True, help_text="Lista di opzioni, es. ['a) Opzione 1', 'b) Opzione 2']", null=True, verbose_name='Opzioni (per domande chiuse)')),
                ('correct_answer', models.CharField(help_text='Per chiuse: lettera (a,b,c,d); per aperte: testo esatto', max_length=10, verbose_name='Risposta corretta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Domanda Quiz',
                'verbose_name_plural': 'Domande Quiz',
                'ordering': ['order'],
            },
        ),
    ]
